### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by lucabe72** [lalbornoz/midipix_build#10]
The build fails when trying to download some non-existing git repository.
Maybe the script should be updated to reflect a new repository layout?

**Comment by lalbornoz** [comment]
See https://github.com/lalbornoz/midipix_build/issues/8.

**Comment by lucabe72** [comment]
So. you distribute on github some scripts for building "midipix"... The
README provided with the scripts does not mention that some components of
midipix cannot be downloaded...
And when people realize this, you invite them to join some IRC channel? Why
cannot you just write the right URL in the scripts? Or at least mention
this funny procedure in the README...

**Comment by midipix** [comment]
The information regarding two repositories still being internal is both on midipix.org and in the README file. This has thus far worked very well for everyone involved (namely core devs and the project's growing community), and ensures that those who decide to build the entire (pre-alpha) distro make their decision knowing exactly where development currently stands, where to get advice, help, and additional information, and what to expect.

**Comment by lucabe72** [comment]
Ok; your README does not contain any information about this, but if it
works well for everyone involved, I give up.

**Comment by midipix** [comment]
The information used to be in the README, but admittedly it is not there right now, so thanks for the catch (./build.sh -h does refer to DEFAULT_GITROOT_HEAD, which I agree only helps if you're already somehow familiar with the build process).

As for <<giving up>> and <<if it works well for everyone involved>> -- the reason it works for everyone involved is that the people who are interested in early (pre-alpha) testing of the framework are also interested in being part of the conversation that shapes the project, as well as help with development to one extent or another. If this speaks to you then please join us on irc, otherwise revisit at release time.

**Comment by midipix** [comment]
Note added in 93594db. Thanks again for the catch.
