### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by JL2210** [lalbornoz/midipix_build#9]
I just cloned your repository and ran `./build.sh -a nt32 -b release`, but the "host" builds seem to be using the native tools to compile Midipix. Am I doing anything wrong?

**Comment by midipix** [comment]
Since midipix_build generates both the cross-compilation environment and the distro's native environment, the _host prefix (and -host- in the package's workdir) was chosen for all local/cross tools, and no prefix (and -native- in the package's workdir) for the distro's native tools. The immediate alternative to _host, namely _cross, would have been tricky and/or misleading since some of the local tools that are built in order to satisfy build dependencies of other packages  (for instance file(1)) have nothing to do with cross-compilation.

Unlike the nt64 cross- and native environments, the nt32 environment currently needs some testing and adjustments, and is thus not expected to work out of the box, at least not at the distro level. If all you're looking for is a cross-compilation environment and a working libc, however, then that should work.

Either way, you might want to consider joining the #midipix channel on the freenode irc network, get help with the build process, and provide feedback on the nt32 distro build until it succeeds in its entirety.

**Comment by JL2210** [comment]
How do I join the "freenode irc network"? I'm getting this: `[15:31] == Cannot send to nick/channel: #midipix` on http://webchat.freenode.net/
